In [ ]:
import numpy as np

## Exercício 1

Crie um array 5x5 com a sequência 1...25 (incluso) e faça a soma dos elementos da diagonal.

In [77]:
########################
# Inicio do seu codigo #
########################
import numpy as np

a = np.arange(1,26)
b = a.reshape(5,5)
print (b)
#print (a)

dp = np.sum(a[0:25:6])
ds = np.sum(a[4:24:4])
total = dp + ds

#print (dp)
#print (ds)
print ('A SOMA DA DIAGONAL PRINCIPAL É: {}'.format(dp))
print ('A SOMA DA DIAGONAL SECUNDÁRIA É: {}'.format(ds))
print ('A SOMA DAS DIAGONAIS É: {}'.format (total))


########################
#   Fim do seu codigo  #
########################

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
A SOMA DA DIAGONAL PRINCIPAL É: 65
A SOMA DA DIAGONAL SECUNDÁRIA É: 65
A SOMA DAS DIAGONAIS É: 130


## Exercício 2

Crie um array 5x5 com a sequência de núemeros pares entre 0...50 (incluso) e faça as seguintes operações:
 1. Soma das linhas
 2. Soma das colunas
 3. Média dos elementos da última linha
 4. Média dos elementos da última coluna

In [94]:
########################
# Inicio do seu codigo #
########################
import numpy as np

c = np.arange(2, 51, 2)
#print (c)
d = c.reshape(5, 5)
print (d)

print ('Soma das linhas: {}'.format(np.sum(d, axis=0)))
print ('Soma das colunas: {}'.format(np.sum(d, axis=1)))
print ('Média dos elementos da última linha:{}'.format(np.mean(d[-1, : ])))
print ('Média dos elementos da última coluna:{}'.format(np.mean(d[ : , 4])))

########################
#   Fim do seu codigo  #
########################

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
Soma das linhas: [110 120 130 140 150]
Soma das colunas: [ 30  80 130 180 230]
Média dos elementos da última linha:46.0
Média dos elementos da última coluna:30.0
